# coding=utf-8

# Note: Recommend using same scaling factors for both ale and epi. The options to use distinct ones
# exist mainly for development purposes.
ALE_UNCERTAINTY_SCALING_DEFAULT = 2.0
EPI_UNCERTAINTY_SCALING_DEFAULT = 2.0

THREE_DIM_LW = 0.65
COLOR_LINE_3D_ALPHA = 0.9
MARKERSIZE_OBSERVATIONS = 1.0
MARKERSIZE_PREDICTIONS = 1.0

COLOR_ENVIRONMENT = "red"
# COLOR_ENVIRONMENT = "firebrick"
COLOR_GROUND_TRUTH = COLOR_ENVIRONMENT
COLOR_GROUND_TRUTH_ALPHA = 1.0

# COLOR_GROUND_TRUTH_NOISE_BLUR = ["orange", "gold", COLOR_ENVIRONMENT]
# COLOR_GROUND_TRUTH_NOISE_BLUR = ["yellow", "orange", COLOR_ENVIRONMENT]
COLOR_GROUND_TRUTH_NOISE_BLUR = ["red", "yellow", COLOR_ENVIRONMENT]
COLOR_GROUND_TRUTH_NOISE_BLUR_ALPHA = 0.9
COLOR_GROUND_TRUTH_NOISE_BLUR_MARKERSIZE = 0.9

COLOR_OBSERVATIONS = COLOR_ENVIRONMENT
COLOR_OBSERVATIONS_ALPHA = 0.6

# COLOR_PREDICTIONS = "royalblue"
# COLOR_PREDICTIONS = "dodgerblue"
COLOR_PREDICTIONS = "blue"
COLOR_PREDICTIONS_ALPHA = 0.5

COLOR_EPI = "yellow"
# COLOR_EPI = "gold"
# COLOR_EPI = "greenyellow"
COLOR_EPI_ALPHA = 0.6

COLOR_ALE = "blue"
COLOR_ALE_ALPHA = 0.25

