# coding=utf-8

# Note: Recommend using same scaling factors for both ale and epi. The options to use distinct ones
# exist mainly for development purposes.
ALE_UNCERTAINTY_SCALING_DEFAULT = 2.0
EPI_UNCERTAINTY_SCALING_DEFAULT = 2.0

THREE_DIM_LW = 0.65
COLOR_LINE_3D_ALPHA = 0.7
MARKERSIZE_OBSERVATIONS = 1.0
MARKERSIZE_PREDICTIONS = 1.0

# COLOR_ENVIRONMENT = "crimson"
COLOR_ENVIRONMENT = "red"
# COLOR_ENVIRONMENT = "orangered"
# COLOR_ENVIRONMENT = "r"

COLOR_GROUND_TRUTH = COLOR_ENVIRONMENT
COLOR_GROUND_TRUTH_ALPHA = 0.5

# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = "goldenrod"
# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = "darkorange"
# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = "yellow"
# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = "orangered"

# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = "gold"
# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = "orange"
# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = "orangered"
# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = COLOR_ENVIRONMENT
# COLOR_GROUND_TRUTH_NOISE_BLUR_l2 = "orangered"
# COLOR_GROUND_TRUTH_NOISE_BLUR_l2 = "orange"
# COLOR_GROUND_TRUTH_NOISE_BLUR = ["orange", "red", COLOR_ENVIRONMENT]
# COLOR_GROUND_TRUTH_NOISE_BLUR = ["red", "yellow", COLOR_ENVIRONMENT]
# COLOR_GROUND_TRUTH_NOISE_BLUR = ["orangered", "gold", COLOR_ENVIRONMENT]
# COLOR_GROUND_TRUTH_NOISE_BLUR = ["gold", "yellow", COLOR_ENVIRONMENT]
# COLOR_GROUND_TRUTH_NOISE_BLUR = ["yellow", "orange", COLOR_ENVIRONMENT]
# COLOR_GROUND_TRUTH_NOISE_BLUR = ["yellow", "orangered", COLOR_ENVIRONMENT]
# COLOR_GROUND_TRUTH_NOISE_BLUR = ["orange", "orangered", COLOR_ENVIRONMENT]
COLOR_GROUND_TRUTH_NOISE_BLUR = ["orangered", "orange", COLOR_ENVIRONMENT]
# COLOR_GROUND_TRUTH_NOISE_BLUR = ["orange", "gold", COLOR_ENVIRONMENT]
COLOR_GROUND_TRUTH_NOISE_BLUR_ALPHA = 0.7
COLOR_GROUND_TRUTH_NOISE_BLUR_MARKERSIZE = 0.8

# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = "orange"
# COLOR_GROUND_TRUTH_NOISE_BLUR_ALPHA = 0.75
# COLOR_GROUND_TRUTH_NOISE_BLUR_MARKERSIZE = 1.0

# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = "gold"
# COLOR_GROUND_TRUTH_NOISE_BLUR_ALPHA = 0.35
# COLOR_GROUND_TRUTH_NOISE_BLUR_MARKERSIZE = 0.8
# COLOR_GROUND_TRUTH_NOISE_BLUR_l1 = "orange"
# COLOR_GROUND_TRUTH_NOISE_BLUR_ALPHA = 0.8
# COLOR_GROUND_TRUTH_NOISE_BLUR_MARKERSIZE = 0.7

COLOR_OBSERVATIONS = COLOR_ENVIRONMENT
COLOR_OBSERVATIONS_ALPHA = 0.6

# COLOR_PREDICTIONS = "royalblue"
# COLOR_PREDICTIONS = "dodgerblue"
COLOR_PREDICTIONS = "blue"
COLOR_PREDICTIONS_ALPHA = 0.5

# COLOR_EPI = "yellow"
COLOR_EPI = "gold"
# COLOR_EPI = "greenyellow"
COLOR_EPI_ALPHA = 0.6

COLOR_ALE = "blue"
COLOR_ALE_ALPHA = 0.25

