# coding=utf-8

ALE_UNCERTAINTY_SCALING_DEFAULT = 2.0
EPI_UNCERTAINTY_SCALING_DEFAULT = 10.0

THREE_DIM_LW = 0.65
COLOR_LINE_3D_ALPHA = 0.7
MARKERSIZE_OBSERVATIONS = 1.0
MARKERSIZE_PREDICTIONS = 1.0

COLOR_GROUND_TRUTH = "red"
COLOR_GROUND_TRUTH_ALPHA = 0.5

COLOR_OBSERVATIONS = "red"
COLOR_OBSERVATIONS_ALPHA = 0.6

# COLOR_PREDICTIONS = "royalblue"
# COLOR_PREDICTIONS = "dodgerblue"
COLOR_PREDICTIONS = "blue"
COLOR_PREDICTIONS_ALPHA = 0.5

# COLOR_EPI = "greenyellow"
# COLOR_EPI = "yellow"
COLOR_EPI = "gold"
COLOR_EPI_ALPHA = 0.6

COLOR_ALE = "blue"
COLOR_ALE_ALPHA = 0.25

